Switch main to 6.1 and add automated refresh to maintenance_6.0 branch
rancher/elemental-channels pull request #53
Opened 2024-11-08 11:34 UTC by davidcassany

2024-11-08 12:58 UTC, davidcassany reviewed
Note that if we merge this we must create a new `v1.6` branch from main.

2024-11-08 12:58 UTC, davidcassany commented on config.yaml
> +    limit: 1
Only one because we want to publish GM and once this is out keep adding on top, but not pre-GM

2024-11-11 08:21 UTC, anmazzotti requested changes
All looks good, but may you run the script locally to populate the json files in this PR already? I see the file names changed, but the content is still the same and includes the 6.0 images.

2024-11-11 08:29 UTC, davidcassany commented
Rebased and updated with a refresh execution mually

2024-11-11 08:32 UTC, anmazzotti commented
Nice! Thank you. 
I see that 2 ISO images ended up included, for v2.1.2 and v2.2.2, the limit is 1 per minor version. 
Not sure this is desired. If we don't want to publish the v2.1.2 images then I would remove them from the registry. Alternatively we can implement some sort of filter in the script.
Anyway the PR is good to me now.

2024-11-11 08:32 UTC, anmazzotti approved these changes

2024-11-11 10:32 UTC, davidcassany commented
Agree, there will be a follow up PR to arrange the glitch with the ISO image es.

2024-11-11 10:32 UTC, merged